### ISSUE TITLE
Choosing a CSS framework

### ISSUE THREAD

**Issue by mfrachet** [aya-experience/noName#3]
To provide better experience and an effective UI, we need to choose a CSS framework to use

**Comment by agory** [comment]
Following my recent discovery of bulma(https://bulma.io/), I am motivated to test it on this project. 

Otherwise there is always the simplicity with material ui (https://material-ui-next.com/) which has several React components but there is less to learn.

I'd better avoid bootstrap if possible.

**Comment by mfrachet** [comment]
Let's take bulma ! 😄
